      const screeningRecords = [
        {
          candidateName: "Anil GenAI",
          employeeId: "491EBC751",
          role: "GenAI Developer",
          experience: "5 years",
          skills: "Python, Java, Cloud, AI/ML",
          location: "Bangalore",
          cvUploaded: "Yes",
          status: "Nominated",
          email: "anil.kumar@email.com",
          phone: "+91-9876543210"
        },
        {
          candidateName: "Anil Kumar",
          employeeId: "994EBC987",
          role: "Data Engineer",
          experience: "5 years",
          skills: "Python, Java, Cloud, AI/ML",
          location: "Bangalore",
          cvUploaded: "Yes",
          status: "Nominated",
          email: "manilkumar1909@gmail.com",
          phone: "N/A"
        },
        {
          candidateName: "Arjun",
          employeeId: "112EBC456",
          role: "Software Engineer",
          experience: "10 years",
          skills: "Python, Java, Cloud, AI/ML",
          location: "Bangalore",
          cvUploaded: "Yes",
          status: "Nominated",
          email: "test@email.com",
          phone: "N/A"
        },
        {
          candidateName: "Dheeraj",
          employeeId: "116EBC803",
          role: "Software Engineer",
          experience: "12 years",
          skills: "Python, Java, Cloud, AI/ML",
          location: "Bangalore",
          cvUploaded: "Yes",
          status: "Nominated",
          email: "test@email.com",
          phone: "N/A"
        },
        {
          candidateName: "Kiran",
          employeeId: "302EBC576",
          role: "Software Engineer",
          experience: "10 years",
          skills: "Python, Java, Cloud, AI/ML",
          location: "Bangalore",
          cvUploaded: "Yes",
          status: "Nominated",
          email: "test@email.com",
          phone: "N/A"
        },
        {
          candidateName: "Megha",
          employeeId: "266EBC652",
          role: "Software Engineer",
          experience: "10 years",
          skills: "Python, Java, Cloud, AI/ML",
          location: "Bangalore",
          cvUploaded: "Yes",
          status: "Nominated",
          email: "test@email.com",
          phone: "N/A"
        },
        {
          candidateName: "Nina",
          employeeId: "579EBC600",
          role: "Software Engineer",
          experience: "9 years",
          skills: "Python, Java, Cloud, AI/ML",
          location: "Bangalore",
          cvUploaded: "Yes",
          status: "Nominated",
          email: "test@email.com",
          phone: "N/A"
        },
        {
          candidateName: "Ravi",
          employeeId: "346EBC968",
          role: "Software Engineer",
          experience: "9 years",
          skills: "Python, Java, Cloud, AI/ML",
          location: "Bangalore",
          cvUploaded: "Yes",
          status: "Nominated",
          email: "test@email.com",
          phone: "N/A"
        },
        {
          candidateName: "Sarah",
          employeeId: "949EBC894",
          role: "Software Engineer",
          experience: "10 years",
          skills: "Python, Java, Cloud, AI/ML",
          location: "Bangalore",
          cvUploaded: "Yes",
          status: "Nominated",
          email: "test@email.com",
          phone: "N/A"
        },
        {
          candidateName: "Sony",
          employeeId: "483EBC984",
          role: "Software Engineer",
          experience: "9 years",
          skills: "Python, Java, Cloud, AI/ML",
          location: "Bangalore",
          cvUploaded: "Yes",
          status: "Nominated",
          email: "test@email.com",
          phone: "N/A"
        },
        {
          candidateName: "Vikram",
          employeeId: "417EBC210",
          role: "Software Engineer",
          experience: "11 years",
          skills: "Python, Java, Cloud, AI/ML",
          location: "Bangalore",
          cvUploaded: "Yes",
          status: "Nominated",
          email: "test@email.com",
          phone: "N/A"
        },
        {
          candidateName: "Vilas Rakhe",
          employeeId: "830EBC928",
          role: "Software Engineer",
          experience: "6 years",
          skills: "Python, Java, Cloud, AI/ML",
          location: "Bangalore",
          cvUploaded: "Yes",
          status: "Nominated",
          email: "vilas.rakhe@example.com",
          phone: "N/A"
        },
      ];
